### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by Quickuser** [AdaemmerP/lpirfs#11]
Dr. Adämmer,

When using your package, with an identified shock, I have the following equation:
![image](https://user-images.githubusercontent.com/63939389/81125398-f0898280-8f2f-11ea-8703-a31ef21c5c96.png) 
(lp_lin_iv())

Which one corresponds to the vector of control variables (without h-horizon)? Contemp_data or exog_data? what form do they individually take in the regression structure?

Thank you.

**Comment by AdaemmerP** [comment]
Thanks for your interest in the package!

Both correspond to exogenous data. The difference is that "contemp_data" is exogenous data with contemporaneous impact and "exog_data" is exogenous data with lagged impact. The number of lags for "exog_data" has to be given in "lags_exog".

**Comment by Quickuser** [comment]
Dr. Adämmer,

Contemp_data will be X (t+h)? or just X (t), like the regression above?

And what form would exog_data take? (assuming no lags imposed) I've got confused.

Thanks you.

**Comment by AdaemmerP** [comment]
The impact of "contemp_data" will be at X(t).

**Comment by Quickuser** [comment]
Dr. Adämmer,

So in this case, contemp_data takes the form of X(t) in the regression (so no H subscript), which does not change through the horizons. Can you confirm this?

![image](https://user-images.githubusercontent.com/63939389/81186522-cc1ebc00-8faa-11ea-85f6-3377d5019410.png)

Thanks.

**Comment by AdaemmerP** [comment]
Correct.

**Comment by Quickuser** [comment]
Thank you. One last question, when we add endog_lags, they also do not have H subscript, right?

Thanks.

**Comment by AdaemmerP** [comment]
No, they do not.

**Comment by Quickuser** [comment]
Thank you so much.
