### ISSUE TITLE
`cumul_mult` option for `lp_lin()`

### ISSUE THREAD

**Issue by itamarcaspi** [AdaemmerP/lpirfs#13]
Hi,

Thanks for a very handy package!

Would it be possible to add the `cumul_mult` option for the single time series functions? As I understand, currently, it is only available for the panel data functions.

**Comment by rderayati** [comment]
Hi,
Thank you for this helpful package.
I want to estimate cumulative impulse responses using (yi,t+h − yi,t−1) as the endogenous variable, for function lp_lin_iv() rather than panel data function. As it is calculated in Jorda et al. (2020). But I can not find any option for this estimation, I will be thankful if you guide me for this issue.

**Comment by AdaemmerP** [comment]
Thanks for your interests in the package and the suggestion. The implementation is on the to-do-list.

**Comment by vahidzolf** [comment]
Hi. 
I have a question for cumulative response. I have reproduced the graph of paper "Longer-Run Economic Consequences of Pandemics", Jorda (2020). They mentioned in equation 2 of paper,  (r,t+h − r,t−1) as the endogenous variable. I used the lp_lin_iv function and defining interest rate as my endogenous variable and obtained the same result with the paper for the UK. But the controversary point is that this function does not calculate cumulative response. I wanted to solve this paradoxical issue that how we obtained the "same" result while they estimated cumulative impulse responses using  (r,t+h − r,t−1) as the endogenous variable, and I estimate via the function which does not estimate cumulative response. Both in Jorda paper and my analysis, we calculated it for one country (UK) not for panel data, for this specific figure.
Thanks in advance

**Comment by AdaemmerP** [comment]
Hi, 
with "same results" do you mean the same trajectory of the impulse responses or the exact same numeric values? I neither know the paper by Jorda (2020) nor have I used cumulative responses myself, but I can imagine the trajectories of "normal" and "cumulative reponses" to be similar.

**Comment by AdaemmerP** [comment]
The Github Version now contains an option for *cumul_mult* for lp_lin_iv() and lp_nl_iv() when the number of lags is fixed.

**Comment by itamarcaspi** [comment]
Fantastic! Thanks 👍

**Comment by AdaemmerP** [comment]
The updated package version (0.2.1) is now on CRAN.

**Comment by carlmroth** [comment]
Hi Philipp,
Thanks for the very useful package. I wonder about the reason that the option _cumul_mult_ was in the update only incorporated in lp_lin_iv() and lp_nl_iv() but not in the standard lp_lin() and lp_nl() functions, where the shock matrix is obtained via the Cholesky decomposition.
Thus, I am wondering whether it would be sufficient to update in lp_lin() the definition of yy as below or if it is not as straightforward and would need to be incorporated already in Cholesky decomposition:
yy <- y_lin[h:dim(y_lin)[1], ], for example, in row 353 of lp_lin() to
yy <- dplyr::lead(y_lin, (h - 1)) - dplyr::lag(y_lin, 1), starting from 438 in lp_lin_iv()
Thanks in advance.
