### ISSUE TITLE
How to color

### ISSUE THREAD

**Issue by rderayati** [AdaemmerP/lpirfs#14]
Dear Dr. Adämmer,
I used the function  lp_lin_iv() to estimate the response of GDP and CO2 emission to external shocks. I plot the result using plot_lin(results_lin_iv). 
1)I tried to change the colour but this function does not change the colour while I added the colour argument.
2) I also want to merge the plots. 
Is there any solution to manipulate the plots in the normal way in R?
Thanks in advance.

**Comment by AdaemmerP** [comment]
The plot functions are not intended to be customized. If you want to create individualized plots, I suggest you save the output from the functions and build the figures from scratch. There are some examples on how to merge plots in the vignette of the package:
https://cran.r-project.org/web/packages/lpirfs/vignettes/lpirfs_vignette.html
