### ISSUE TITLE
Shock size in lp_lin_iv

### ISSUE THREAD

**Issue by enemcik** [AdaemmerP/lpirfs#15]
Hello,

First of all, let me acknowledge the quality of the package - it is great and exactly just what I was looking for! 

However, I have not found much information about the shock size in the function lp_lin_iv. I suppose it's a unit shock. Is there any possibility to modify these values? An example could be evaluating variable responses to the monetary policy shock (e.g., 25 basis points increase in a given interest rate). 

Thank you for your clarification.

**Comment by AdaemmerP** [comment]
Thanks for using the package. 

The impulse responses in lp_lin_iv are simply OLS estimates. If you want to measure the reaction to different shock sizes, you should recalibrate your shock series.
