### ISSUE TITLE
Horizons in cumulative panel LP

### ISSUE THREAD

**Issue by TomT-ec** [AdaemmerP/lpirfs#16]
Hi!

First of all many thanks for the fantastic package.

I have a question about horizons which are being used for lp_lin_panel. In the reference manual (page 16) it is stated that the horizons range from 0 to H-1. However, plotting the LP using plot.lpirfs_lin_panel_obj, we obtain an impulse response that starts at 1 on the x-axis.

I wanted to double check whether the lp_lin_panel with cumul_mult = TRUE uses horizons from 0 to H-1 as stated in the reference manual or from 1 to H.

**Comment by AdaemmerP** [comment]
Thanks for using the package. 

*lpirfs* follows the convention by Jordà (2005), namely that the first computed horizon equals h = 0. The x-axis for the figures is labeled from 1 to H, yet the impulse responses are computed for 0 to H-1.
