### ISSUE TITLE
Nonlinear impulse-response functions (s1 & s2)

### ISSUE THREAD

**Issue by gueyenono** [AdaemmerP/lpirfs#17]
I'd like to thank you for a great package with an intuitive interface.

Could you please provide more explanations about the difference between the impulse-response functions produced by `lp_nl()`? More specifically, what is the difference between `irf_s1_*` and `irf_s2_*`? The function documentation talks about their content; however, I was not able to find anything about what they actually are. Any pointer would be greatly appreciated.

Thank you.

**Comment by AdaemmerP** [comment]
The paper contains more information on that:
https://journal.r-project.org/archive/2019/RJ-2019-052/RJ-2019-052.pdf
