### ISSUE TITLE
How to derive NW standard errors for impulse responses?

### ISSUE THREAD

**Issue by chryssaka** [AdaemmerP/lpirfs#18]
Hi,

Could you please give an example of how can I extract the standard errors for the impulse responses that I calculate in lp_lin_iv function? I am new in R and I am using this package for my thesis.

Thank you for creating this package it's very helpful.

**Comment by AdaemmerP** [comment]
The output of the function provides the impulse responses as well as the upper and lower bounds which uses the standard errors. Just type:

results_lin_iv$irf_lin_mean
results_lin_iv$irf_lin_low
results_lin_iv$irf_lin_up

**Comment by chryssaka** [comment]
I need to present in a table next to the impulse responses (results_lin_iv$irf_lin_mean) just the standard errors. (the lower and up bounds I will use them in a plot. )

Thank you for your immediate reply.

**Comment by AdaemmerP** [comment]
Just take the difference and divide by the value you gave to the function for 'confint':

(results_lin_iv$irf_lin_up - results_lin_iv$irf_lin_mean)/confint
