### ISSUE TITLE
How to make changes in graphs/impulse response graphs

### ISSUE THREAD

**Issue by steve-1977** [AdaemmerP/lpirfs#20]
Hi,

  How do I make changes in the impulse response graphs? For example I want to make the impulse response lines bolder or add markers. How do I do that?

Many thanks  in advance.

Steve

**Comment by steve-1977** [comment]
Is there a way to make changes in the impulse response graphs like change of colour of the lines, type of lines and so on...

**Comment by AdaemmerP** [comment]
The plot function is not intended for customization. For customized plots you should use the provided impulse responses and confidence bands and do the figures yourself.
