### ISSUE TITLE
Inquiry about lpirfs, horizons

### ISSUE THREAD

**Issue by husang7** [AdaemmerP/lpirfs#23]
Hi!

Thank you for creating such a useful package. It has been very helpful.

I just wanted to ask about the horizons of irfs that the package gives. Does h=1 mean the response of y_{t+1} to the shock_{t}?

If so, is there any way I could see the response of y_{t} to the shock_{t}? In other words, I want to know the response "on impact" (h=0).

Thank you so much.

Best,

Husang Kim

**Comment by AdaemmerP** [comment]
Thanks for using the package. 
It is written in the paper that "lpirfs follows the convention by Jordà (2005), namely that the first horizon,
denoted on the x-axis, equals h = 0" (https://journal.r-project.org/archive/2019/RJ-2019-052/RJ-2019-052.pdf, page 426).
