### ISSUE TITLE
question on historical decomposition

### ISSUE THREAD

**Issue by pgg1309** [AdaemmerP/lpirfs#25]
Thanks a lot @AdaemmerP for this very useful package. 

I'm trying to implement **historical decomposition** using local projections. 
From the traditional VAR structure it is easy to understand the process having as a starting point the Wold decomposition. 
I was wondering if you have any idea how to calculate *historical decomposition* under the local projection framework. 
Any ideas or reference papers would be welcome.
Thanks

**Comment by AdaemmerP** [comment]
Thanks for your interest in the package. Unfortunately, I am not familiar with the concept of **historical decomposition**, so I cannot be of much help at this point.

**Comment by pgg1309** [comment]
Thanks. 
In a traditional VAR, one can use the Wold theorem [https://en.wikipedia.org/wiki/Wold%27s_theorem](url) allows one to re-write all the endogenous variables as a sum of past innovations. Therefore one can look at the time series of each endogenous variable as a sum of past innovations (shocks) for ALL other equations (endogenous variables). 

Then it allows one to easily construct 'counterfactuals'. For instance, in a standard monetary VAR (output gap, interest rates, inflation) one could build a counterfactual for the output gap excluding (or assuming zero) shocks to interest rates in a given period. 

Given the similarity of the local projections and VAR I though it could be possible to do a similar exercise, but was not sure exactly on how to proceed. Thus my question.

Thanks again for the very useful package. 
Best
