### ISSUE TITLE
Do you please plan to add diagnostics to the lp_lin_panel and lp_nl_panel?

### ISSUE THREAD

**Issue by JeanCarpenter** [AdaemmerP/lpirfs#29]
Hello,

thank you for this package! I am using it while working on my PhD on central banks policy. I do not have access to Stata at my institution so I try it in R. 
I have found the coefficients in the "reg_summaries". However, I am wondering if there is a similar function as in lp_lin and lp_nl for **diagnostics (I have found in the documentation "diagnostics_list")** or if you please plan to add it. 

Otherwise, I would be **very grateful** if you advise me on how I could get it.

Thank you in advance!  

Jeanette

**Comment by AdaemmerP** [comment]
If you use a robust covariance estimator for input _robust_cov = ..._ , the output for _reg_summaries_ will only be the t-tests based on the robust covariance estimators. If you do not use a robust covariance estimator (_robust_cov = NULL_), you get a full summary output in "**reg_summaries**" from the plm package.  Hence, you could run the code again with _robust_cov = NULL_ to get some additional diagnostics.

**Comment by JeanCarpenter** [comment]
oh! I see, thank you very much! 
JC

**Comment by AdaemmerP** [comment]
The new CRAN version (0.2.3) now also returns the full plm-output for each horizon for the panel functions. Hence, you can compute your own summary statistics.

**Comment by JeanCarpenter** [comment]
Thank you that will be very useful, I will try it out soon. 
JC
