### ISSUE TITLE
Use of another model in calculating standard errors in lpirfs::lp_lin()

### ISSUE THREAD

**Issue by taranpreetk** [AdaemmerP/lpirfs#32]
Hello, I appreciate the excellent alternative you've provided for the data-driven Impulse response.

Upon reviewing the code base of the lp_lin() function, I discovered that it relies on Ordinary Least Squares (OLS) for computing the impulse response. However, I'm curious if there's a possibility of employing a different model, such as Random Forest or GAM, to calculate standard errors and subsequently generate impulse responses.

I would greatly appreciate it if you could let me know if this is feasible, and if so, kindly share any helpful tips or insights for implementing this approach. Thank you.

**Comment by AdaemmerP** [comment]
Why would you want to compute the standard errors via Random Forests? The theoretical properties of OLS are well known, which is why the package also sticks to this approach.
