### ISSUE TITLE
Cumul_mult question

### ISSUE THREAD

**Issue by JeanCarpenter** [AdaemmerP/lpirfs#33]
Hello, 

I have a quick question regarding the **cumul_mult** argument. I have reviewed the documentation and if TRUE, I understand that it is estimated via y(t+h) − y(t−1). 

I have been running a model, which gives me very different IRFs (one >0 and one<0, for the whole horizon) when cumul_mult TRUE/FALSE. Is that possible? 

Thank you very much. Kind regards, Jeanette

**Comment by AdaemmerP** [comment]
Unfortunately, this is too case specific, and I do not have an answer to this question.
