### ISSUE TITLE
IV in non-linear panel LP

### ISSUE THREAD

**Issue by eiae** [AdaemmerP/lpirfs#34]
If not mistaken, the current version does not allow to augment the non-linear panel LP with IV (at least there is no option to specify the instrument). Would it be a relatively straight-forward task to implement this (i.e., with already having the existing routines on non-linear LP and the IV setting for panel LP)?

Any guidance would be of help.

**Comment by AdaemmerP** [comment]
I have not looked into that option. You might use `lpirfs` to prepare your data sets and then use the `plm` package on your own for that task.
