### ISSUE TITLE
Option to include lagged forecast errors

### ISSUE THREAD

**Issue by pascalseiler** [AdaemmerP/lpirfs#35]
Many thanks for your great package! As I did not find any information about this, I was wondering if there is an option to recursively include the forecast errors from horizon h−1 in the local projection at horizon h?
This refers to Jorda (2005, p. 166) to increase estimation efficiency: "In principle, the efficiency of these estimators can be improved upon by recursively including the residuals of the stage s-1 local projection as regressors in the stage s local projection."

**Comment by AdaemmerP** [comment]
Thank you for your interest in the package! This feature is not implemented. You would have to implement it yourself by iteratively running the local projections with updated covariates that include the residuals.
