### ISSUE TITLE
Lag length in lp_nl

### ISSUE THREAD

**Issue by Aceampoma** [AdaemmerP/lpirfs#36]
Hello, excellent Package: My question is how do I switch off the lag length and use my fixed lag. ;

esults_nl <- lp_nl(endog_data, 
+                   lags_endog_lin = 12,   # Number of lags for (reduced) linear VAR to obtain shock matrix. 
+                   lags_endog_nl  = 12,   # Number of lags for nonlinear model. 
+                    trend          = 0,    # 0 = no trend, 1 = trend, 2 = trend & trend^2.
+                   shock_type     = 0,  # 0 = standard deviation shock, 1 = unit shock.
+                    confint        = 1.67, # Width of confidence bands: 
+                    # 1 = 68%, 1.67 = 90%, 1.96 = 95%.
+                    hor            = 36,   # Length of irf horizons.
+                    switching      = endog_data$ACLR, # Use inflation rate as switching variable.
+                    use_hp         = TRUE, # Use HP-filter? TRUE or FALSE.   
+                    lambda         = 129,600, # Ravn and Uhlig (2002):
+                    # Anuual data    = 6.25
+                    # Quarterly data = 1600
+                    # Monthly data   = 129,600
+                    gamma          = 6,) 

Error in lp_nl(endog_data, lags_endog_lin = 12, lags_endog_nl = 12, trend = 0,  : 
  Possible lag length criteria are AICc, AIC or BIC or NaN if lag length is specified.

**Comment by AdaemmerP** [comment]
Did you set "lags_criterion = NaN"? Your code is unfortunately not reproducible.

**Comment by Aceampoma** [comment]
No, I have fixed it thank you.
