### ISSUE TITLE
lp_nl

### ISSUE THREAD

**Issue by Aceampoma** [AdaemmerP/lpirfs#37]
Hello, does regime 1 which gives values close to 0, always constitute the high regime of the switching variable and regime 2 which gives values close to 1 constitute the low regime of the switching variable? Thank you.

**Comment by Aceampoma** [comment]
To be clear, if the switching variable assumes a 1-low regime and a 0-high regime?

**Comment by AdaemmerP** [comment]
It depends on the construction of your switching variable. Look at equation (3) in the paper: https://journal.r-project.org/archive/2019/RJ-2019-052/RJ-2019-052.pdf
