### ISSUE TITLE
Lags of the endogenous variable in lp_lin_panel()

### ISSUE THREAD

**Issue by 4Freye** [AdaemmerP/lpirfs#39]
Hello,

Thanks for the package! I was curious if lags of the endogenous variable are supported when working with panel data and using the lp_lin_panel() function.

Though I guess a solution would be to create a lag of the endogenous variable and specify that as one of the exogenous variables?

Kind regards,
Eric

**Comment by AdaemmerP** [comment]
Yes, exactly, your guess is correct. Just add the endogenous variable to the exogenous ones and specify the lags.
