### ISSUE TITLE
truncation parameter in newey_west

### ISSUE THREAD

**Issue by mmkuang** [AdaemmerP/lpirfs#4]
In Jorda (2005), the Newey-West Lag length is 1 + p + h, where h is length of the impulse response (h = 24 in Jorda (2005)), p is lag length in the VAR. The well-received textbook Introduction to Econometrics by Stock & Watson (2015) set the truncation parameter equal 0.75 T^(1/3).

In lp_lin function:
for (h in 1:(specs$hor)){
      nw_results = lpirfs::newey_west(yy[, k], xx, h)
}

So, if h = 1, truncation parameter = 1
      if h = 2, truncation parameter = 2
      ......
I think this does not match the existing literature. Usually, the truncation parameter is fixed and related to the length of the sample.

**Comment by AdaemmerP** [comment]
Thanks for the comment. 

Actually, in the original paper Jordà (2005, p. 171) writes that "The Newey-West lag correction is selected to increase with s, the horizon of the impulse response being considered." His truncation parameter is thus not fixed. 

The approach in *lpirfs* is identical and furthermore based on Ramey and Zubairy (2018) who also set the truncation parameter equal to h:
https://www.journals.uchicago.edu/doi/suppl/10.1086/696277
Stock and Watson (2018) set the truncation parameter equal to h+1 when using local projections:
https://www.princeton.edu/~mwatson/papers/Sargan_Lecture_Stock_Watson_20180104.pdf

Given that there is no optimal way for finding the truncation parameter and given that the package allows to replicate empirical results by Jordà (2005) and Ramey and Zubairy (2018), I think the approach is totally in line with the existing literature.
