### ISSUE TITLE
Regarding confidence intervals 

### ISSUE THREAD

**Issue by mandarpriya** [AdaemmerP/lpirfs#40]
Sir i really appreciate for the library lpirfds and it has been very useful I was facing the issue of how to obtain the confidence intervals. As in the source code given by you it is there , but then it isn not extracted in the putput. 
So if suppose in analysis i want to use the confidence interval then what is the way for doing it.
Thanks & Regards

Mandar

**Comment by AdaemmerP** [comment]
Can you please share a reproducible example or write which function you are referring to.
