### ISSUE TITLE
Fitted y values in output

### ISSUE THREAD

**Issue by Asha-ghub** [AdaemmerP/lpirfs#42]
I'd like to retrieve the y-hat values from the LP output, however, I am not certain that it produces them and where they would be. My guess so far has irf_lin_mean in the results_lin dropdown, but I am unsure. Additionally, what does a computationally singular error mean and how would I go about resolving it?

**Comment by AdaemmerP** [comment]
The panel functions return the entire regression outputs of the plm package.
