### ISSUE TITLE
lp_lin.R

### ISSUE THREAD

**Issue by GushchiaNasty** [AdaemmerP/lpirfs#5]
Hi Phillip.
Maybe I wrong, but I think that the next code isn't correct:

# First value of horizon is merely the shock
      irf_lin_mean[, 1, i]   <- t(d[, i])
      irf_lin_low[,  1, i]   <- irf_lin_mean[, 1, i]
      irf_lin_up[,   1, i]   <- irf_lin_mean[, 1, i]

Why are you set up for the up and low confidence interval value equal mean? 
You calculate the 1'st dot of IRF, but the error shouldn't be equal it, isn't it?

**Comment by AdaemmerP** [comment]
Thanks for the comment. 
The first horizon actually equals h = 0, thus the shock. There are no confidence bands at this stage 
which is why I set the values of the bands equal to irf_lin_mean. You can see that when you plot the impulse responses.
