### ISSUE TITLE
Cumulative Impulse Responses

### ISSUE THREAD

**Issue by nreigl** [AdaemmerP/lpirfs#7]
Hi, 

are there any theoretical considerations regarding a possible implementation of cumulative Impulse Response Functions for the linear local projection method?

**Comment by AdaemmerP** [comment]
Thank you for your interest in the package!

I haven't considered implementing cumulative multipliers for the other functions besides the panel ones. The wording "cumulative multipliers" in the package might be somewhat misleading, as it does not sum up the values of the endogenous variable but rather estimates the differences in regards to the first lag of the endogenous variable. The formula for computing them is given in the description of the functions. However, I'll consider renaming the option in a future version.

**Comment by nreigl** [comment]
Dear Philipp, 

thank you for the response. Maybe I was not clear in my questions. I was thinking if it is possible to compute the cumulated impulse response coefficients to get an idea of the overall long-run effect of the shock.

**Comment by AdaemmerP** [comment]
No, this option is not included in the package. What functions are you currently using and what paper(s) are you referring to that use it? I might consider the option for a future version.

**Comment by nreigl** [comment]
I'm currently using `lp_lin` to compute linear impulse responses. 

For example: [_Enders et al. (2018)_ ](https://www.uni-heidelberg.de/fakultaeten/wiso/awi/professuren/wipol/forschung.html) seem to use from my understanding local projects to compute cumulative impulse response of output growth to a nowcast error (Figure 2: right Panel). 
 

> Z. Enders, M. Kleemann, and G. J. Muller, “Growth expectations, undue optimism, and short-run ﬂuctuations,” p. 52., July 2018

**Comment by AdaemmerP** [comment]
Thanks for the paper. I do not see any equation how they estimate the local projections. 
I'll keep you posted regarding future implementation.

**Comment by alemello14** [comment]
Hi,
Have you developed a cumulative option for lp_lin()?
I got it the cumulative IRFs, since it's just do a cumsum() in irf_lin_mean.
However, that's not the case for the CIs. 
In fact, even the Enders paper above seems to just sum the CIs, which is wrong.
Many thanks!
