### ISSUE TITLE
Information Criterion issues

### ISSUE THREAD

**Issue by Mdsdms** [AdaemmerP/lpirfs#9]
Hi, 
When using lags_criterion='AIC', I met an issue in my output with the function summary(results_lin)[[1]][4] and summary(results_lin). This problem does not arise when using a defined number of lags. There is no issues with the plot. 
Thanks in advance for your response
summary(results_lin)[[1]][4]
## NULL
summary(results_lin)

**Comment by AdaemmerP** [comment]
Thanks for your comment! It seems that the output has been saved twice as a list. 
I fixed the issue and uploaded the updated version on GitHub. Can you install it and check whether it solved your issue?

**Comment by Mdsdms** [comment]
I tested the updated package on Github and the issue is fix. Thanks a lot.
